"""dispute system

Revision ID: c60e3b325e86
Revises: 0cc69c6eee67
Create Date: 2016-01-06 09:23:59.714878

"""

# revision identifiers, used by Alembic.
revision = 'c60e3b325e86'
down_revision = '0cc69c6eee67'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('open', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('reports_mismatch'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('result', sa.Enum('won', 'lost', 'draw'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id', 'ticket_id')
    )
    op.create_index(op.f('ix_report_game_id'), 'report', ['game_id'], unique=False)
    op.create_index(op.f('ix_report_player_id'), 'report', ['player_id'], unique=False)
    op.create_index(op.f('ix_report_ticket_id'), 'report', ['ticket_id'], unique=False)
    op.add_column('chat_message', sa.Column('admin_message', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('chat_message', sa.Column('ticket_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chat_message_ticket_id'), 'chat_message', ['ticket_id'], unique=False)
    op.create_foreign_key(None, 'chat_message', 'ticket', ['ticket_id'], ['id'])
    op.drop_column('game', 'report_try')
    op.drop_column('game', 'report_creator_date')
    op.drop_column('game', 'report_opponent_date')
    op.drop_column('game', 'report_creator')
    op.drop_column('game', 'report_opponent')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_message', type_='foreignkey')
    op.drop_index(op.f('ix_chat_message_ticket_id'), table_name='chat_message')
    op.drop_column('chat_message', 'ticket_id')
    op.drop_column('chat_message', 'admin_message')
    op.drop_index(op.f('ix_report_ticket_id'), table_name='report')
    op.drop_index(op.f('ix_report_player_id'), table_name='report')
    op.drop_index(op.f('ix_report_game_id'), table_name='report')
    op.drop_table('report')
    op.drop_table('ticket')
    ### end Alembic commands ###
